# Generated by Django 5.0.6 on 2024-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('duracion_minutos', models.IntegerField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_lecciones/')),
            ],
        ),
    ]
